name: RunicQuests
description: Runic Realms Questing Plugin, by Excel
version: 1.0
main: com.runicrealms.plugin.runicquests.RunicQuests
depend:
  - RunicNpcs
  - RunicChat
  - RunicCore
  - RunicProfessions
  - RunicRestart
  - RunicItems
  - RunicCommon
  - RunicDatabase
  - MythicMobs
  - PlaceholderAPI
  - HolographicDisplays
api-version: 1.15
#commands:
#  quests:
#    description: Shows you your current objectives
#    aliases: [ quest, objective, objectives ]
#  resetquests:
#    description: Resets a player's quest data
#    aliases: [ questsreset, resetquest, questreset, rq, qr ]
#  completequest:
#    description: Completes a player's quest
#    aliases: [ questcomplete, cq, qc ]
#  questtrigger:
#    description: Command for quest triggers
#    aliases: [ qt ]